cluster_name: testCluster2
name: test1
steps:
- destination:
    clusterName: optional
    namespace: str
  name: step1
  prune: false
  tests:
  - {}
- destination:
    clusterName: optional
    namespace: str
  name: step2
  prune: false
  tests:
  - {}
- destination:
    clusterName: optional
    namespace: str
  name: step3
  prune: false
  tests:
  - {}
