apiVersion: argoproj.io/v1alpha1
destination:
  clusterName: optional
  namespace: str
kind: application
metadata:
  annotations:
    atlas-argo-sync-prune: false
  name: step1-app
  namespace: argocd
spec:
  project: default
  source:
    path: test
    repoURL: test
