apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-to-dev3-app
  namespace: argocd
  annotations:
    prune: false
spec:
  project: default
  source:
    repoURL: https://github.com/gsharma30/atlasexample.git
    targetRevision: main
    path: testTeam/test_pipeline100/deploy-to-dev3/argo/argo_manifest
  destination:
    server: in-cluster
    namespace: dev
