apiversion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step1-app
  namespace: argocd
  annotations:
    prune: false
spec:
  project: default
  source:
    repoURL: https://github.com/gsharma30/atlasexample.git
    targetRevision: main
    path: testTeam/test_pipeline/step1/argo/argo_manifest
  destination:
    server: ""
    namespace: ""
