name: test_pipeline100
cluster_name: in-cluster
steps:
- name: deploy-to-dev5
  application_path: deploy-to-dev5/argo/deploy-to-dev5-app.yml
  tests:
  - filename: verifyendpoints.sh
    filetype: ""
    type: inject
    image: ""
    commands:
    - sh
    - -c
    - ./verifyendpoints.sh
    before: "false"
    namespace: ""
    variables: []
  - filename: verifyendpoints.sh
    filetype: ""
    type: inject
    image: ""
    commands:
    - sh
    - -c
    - ./verifyendpoints.sh
    before: "false"
    namespace: ""
    variables: []
