name: test_pipeline100
cluster_name: in-cluster
steps:
- name: deploy-to-dev3
  application_path: deploy-to-dev3/argo/deploy-to-dev3-app.yml
  tests:
  - before: "false"
    commands:
    - sh
    - -c
    - ./verifyendpoints.sh
    path: verifyendpoints.sh
    type: inject
