cluster_name: testCluster
name: pipeline2
steps:
- destination:
    clusterName: cluster3
    namespace: str
  name: step1
  prune: false
  tests: []
- destination:
    clusterName: optional
    namespace: str
  name: step2
  prune: false
  tests: []
- destination:
    clusterName: cluster4
    namespace: str
  name: step3
  prune: false
  tests:
  - {}
